version: "3.8"

name: wd_setup

services:
  db:
    image: postgres:latest
    container_name: db
    env_file: .env.local
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - ./db-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env.local
    container_name: pg-admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pg-network
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/

networks:
  pg-network:
